[project]
name = "my-local-project"
version = "0.1.0"
dependencies = ["scikit-learn (==1.6.1)"]
requires-python = ">=3.9"

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"
